  - label: ":freebsd: FreeBSD"
    agents:
      queue: freebsd
    command:
      - .buildkite/build
      - .buildkite/test
      - .buildkite/annotate
    env:
      BUILD_STATS_NO_COLOR: "1"
    plugins:
      - *merged-pr-plugin
